local Datatables = {}

Datatables["S1"] = {
  ["Locations"] = {"Abyssal Zenith","Ancient Archives","Ancient Isle Ocean","Ancient Isle Pond","Ancient Isle Waterfall","Atlantean Storm","Atlantis Ocean","Blue Moon - First Sea","Brine Pool","Brine Pool Water","Calm Zone","Challengers Deep","Cryogenic Canal","Deep Ocean","Desolate Deep","Ethereal Abyss","Forsaken Shores","Forsaken Shores Ocean","Forsaken Shores Pond","Forsaken Veil","Frigid Cavern","Glacial Grotto","Grand Reef","Harvesters Spike","Keepers Altar","Kraken Pool","Lava","Moosewood Docks","Moosewood Ocean","Moosewood Ocean Mythical","Moosewood Pond","Mushgove Water","Notes Island Pool","Ocean","Overgrowth Caves","Poseidon Pool","Roslit Bay","Roslit Bay Clam","Roslit Bay Ocean","Roslit Pond","Roslit Pond Seaweed","Roslit Bay","Scallop Ocean","Snowcap Ocean","Snowcap Pond","Sunken's Depth","Sunstone","Sunstone Hidden","Terrapin Ocean","Terrapin Olm","The Arch","The Depths","Vertigo","Volcanic Vents","Zeus Pool"},
  ["Overrides"] = {"Animal Pool","Great White Shark","Great Hammerhead Shark","Whale Shark","Megalodon Default","Megalodon Ancient","The Kraken Pool","Orcas Pool","Forsaken Veil - Scylla","Whales Pool","Isonade","The Depths - Serpent"},
  ["Locations2"] = {["AFK/Mythical"]=CFrame.new(260,138,45),["Altar"]=CFrame.new(1308,-800,-95),["Ancient"]=CFrame.new(6060,200,285),["Arch"]=CFrame.new(996,136,-1237),["Atlantean Storm"]=CFrame.new(-3838,137,345),["Atlantis"]=CFrame.new(-4256,-599,1795),["Blue Moon"]=CFrame.new(2741,136,2513),["Brine"]=CFrame.new(-1799,-137,-3431),["Cay"]=CFrame.new(1740,150,-2419),["Crafting"]=CFrame.new(-3163,-743,1689),["Depths"]=CFrame.new(881,-733,1247),["Desolate"]=CFrame.new(-1655,-209,-2846),["Earmark"]=CFrame.new(1232,145,534),["Forsaken Shores"]=CFrame.new(-2496,137,1541),["Haddock"]=CFrame.new(-547,160,-453),["Kraken Pool"]=CFrame.new(-4380,-992,2047),["Moosewood"]=CFrame.new(386,139,253),["Mushgrove"]=CFrame.new(2582,136,-754),["Northern"]=CFrame.new(19538,137,5305),["Peak"]=CFrame.new(20025,1141,5527),["Reef"]=CFrame.new(-3566,155,535),["Roslit Bay"]=CFrame.new(-1462,138,708),["Snowcap"]=CFrame.new(2633,147,2464),["Spike"]=CFrame.new(-1254,141,1563),["Statue"]=CFrame.new(26,164,-1043),["Sunstone"]=CFrame.new(-922,137,-1117),["Terrapin"]=CFrame.new(-162,149,1932),["Terrapin Cave"]=CFrame.new(49,157,2001),["Upper Snowcap"]=CFrame.new(2817,285,2553),["Vertigo"]=CFrame.new(-111,-511,1141),["Volcano"]=CFrame.new(-1899,179,310)}
}
Datatables["S2"] = {
    ["Locations"] = {"Azure Lagoon","Blue Moon - Second Sea","Emberreach","Emberreach Lava","Emberreach Ponds","Isle of New Beginnings","Lushgrove","Open Ocean","Pine Shoal","The Cursed Shores","Waveborne"},
    ["Overrides"] = {"Animal Pool","Sea Leviathan Pool"},
    ["Locations2"] = {["Azure Lagoon"]=CFrame.new(1342,84,2107),["Blue Moon"]=CFrame.new(1371,116,-603),["Cursed Shores"]=CFrame.new(-271,85,2066),["Emberreach"]=CFrame.new(2373,88,488),["Emberreach Lava"]=CFrame.new(3398,198,575),["Emberreach Pond"]=CFrame.new(2813,168,557),["Isle Of New Beginnings"]=CFrame.new(-349,85,-441),["Lushgrove"]=CFrame.new(1124,111,-575),["Pine Shoals"]=CFrame.new(1154,92,600),["Waveborne"]=CFrame.new(432,89,779)}
}
Datatables["Locations"] = {"Abyssal Zenith","Ancient Archives","Ancient Isle","Animals1","Animals2","Archeological Site","Ashfall","Atlantean Storm","Atlantis","Azure Lagoon","Blue Moon - First Sea","Blue Moon - Second Sea","Brine Pool","Calm Zone","Challenger's Deep","Cryogenic Canal","Crypt","Cults Curse","Desolate Deep","Emberreach Lava","Emberreach Ponds","Emberreach","FischFright","Fischgiving","Fischmas","Forsaken Shores","Frigid Cavern","Glacial Grotto","Golden Tide","Grand Reef","Isle of New Beginnings","Keepers Altar","Lucky Event","Lushgrove","Moosewood","Mushgrove","Ocean","Octophant","Open Ocean","Overgrowth Caves","Pine Shoal","Roslit Volcano","Roslit","Snowcap","Sunstone","Terrapin","The Cursed Shores","The Depths","Veil of the Forsaken","Vertigo","Volcanic Vents","Waveborne","Winter's Edge"}
Datatables["Fish"] = loadstring(game:HttpGet("https://raw.githubusercontent.com/Lythicals/script/refs/heads/main/newdatatables"))().Fish
-- thanks lyth

return Datatables
